### PR TITLE
Feature: Extended argument types

### PR DESCRIPTION
**Pull request by adzialocha**

### CODE REVIEW

**Comment by adzialocha** [comment]
Thank you @davidgranstrom for this great feature! I've created the PR here now as you mentioned you are fine with merging it.

There has been some minor changes around npm dependencies and CI lately, also the lib folder is not checked-in anymore. I'm happy to review the PR if you could fix the conflicts whenever you find time.

**Comment by davidgranstrom** [comment]
@adzialocha Thanks! I'll sort out the conflicts and get back to you soon.

**Comment by davidgranstrom** [comment]
@adzialocha I've rebased the branch. All tests are passing locally but not the linter (unrelated to this PR though).

```
ESLint: 7.17.0

TypeError: Cannot read property 'value' of null
Occurred while linting /Users/dkg/code/javascript/osc-js/src/atomic/string.js:69
 ```

**Comment by adzialocha** [comment]
> @adzialocha I've rebased the branch. All tests are passing locally but not the linter (unrelated to this PR though).

Oha! It looks like a bug in `babel-eslint` but even an upgrade didn't solve it. I could fix it by doing a fresh reinstall of all packages after deleting the `package-lock.json` (see related issue here: https://github.com/babel/babel/issues/10904). The fix is pushed to master: https://github.com/adzialocha/osc-js/commit/d5693c6cc4013fe39658a233ca37f44ff3e4b03a

**Comment by davidgranstrom** [comment]
Okay! Lint is now passing after rebase and reinstall. I think this is ready for review!

**Comment by adzialocha** [comment]
10 million years later I could finally look at this, it looks super! Thank you so much @davidgranstrom!

**Pull request merged**
